const staticContent = {
  "Vorhangschiene_Tutorialsteps": [
    {
      "Schritt": 0,
      "Visual": null,
      "Title": "Übersicht",
      "Description": "aller Einzelteile",
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 3,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 2,
      "js_name": "UbersichtAction",
      "active_bone": null
    },
    {
      "Schritt": 1,
      "Visual": null,
      "Title": "Schienenteile",
      "Description": "mit zwei Verbindungsstiften zentriert und mit einem Schienenverbinder kraftschlüssig verbinden",
      "SlotNut": null,
      "Notification_1": "Später benötigte Einschubnutensteine vor dem Verbinden der Schienenteile in Schienennut schieben.",
      "Notification_2": "Der Verbindungsstift Edelstahl kann den Standard-Verbindungs-stift dort ersetzen, wo häufiger Auf- und Abbau der Schienen vorkommt (erleichtert das Auseinandernehmen der Schienenteile).",
      "Warning": null,
      "Tool_1": "Hammer",
      "Tool_2": "Zange",
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.33,
      "cam_y": 0.2,
      "cam_z": -0.13,
      "target_x": 0,
      "target_y": 0,
      "target_z": -0.4328,
      "radius": 0.1899,
      "js_name": "Schienenteile",
      "active_bone": "Schienenverbindungsstift_01"
    },
    {
      "Schritt": 2,
      "Visual": null,
      "Title": "Rohrhaken",
      "Description": "an den Abhängungen montieren",
      "SlotNut": "x",
      "Notification_1": "Die Rohrhaken so einstellen, dass sie in eine Richtung geöffnet sind.",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": "Zange",
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.4621,
      "cam_y": 0.1329,
      "cam_z": -0.7031,
      "target_x": 0.0442,
      "target_y": 0.224,
      "target_z": -0.3291,
      "radius": 0.1963,
      "js_name": "Rohrhaken",
      "active_bone": "Rohrhaken_2"
    },
    {
      "Schritt": 3,
      "Visual": null,
      "Title": "Beide Zugwagen",
      "Description": "in der Mitte gegenläufig auf jeweils einer Seite einsetzen",
      "SlotNut": null,
      "Notification_1": "Auf die richtige Positionierung der Bügel achten. ",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.29,
      "cam_y": 0.26,
      "cam_z": 0.39,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 0.35,
      "js_name": "Zugwagen",
      "active_bone": "Laufwagen_ueberzugbuegel_1"
    },
    {
      "Schritt": 4,
      "Visual": null,
      "Title": "Zweiradlaufwagen",
      "Description": "auf beiden Seiten je nach Länge anbringen",
      "SlotNut": null,
      "Notification_1": "gem. Ösenabstand alle 200 mmm (bei einem glatten Vorhang)",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.584,
      "cam_y": 0.316,
      "cam_z": -1.745,
      "target_x": 0,
      "target_y": 0,
      "target_z": -1,
      "radius": 0.5472,
      "js_name": "Zweilaufradwagen",
      "active_bone": "Zweilaufradwagen_8"
    },
    {
      "Schritt": 5,
      "Visual": null,
      "Title": "Umlenkrolle",
      "Description": "auf der gegenüberliegenden Seite anbringen an dem gezogen wird",
      "SlotNut": "x",
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "Schraubenschlüssel/Ratsche SW 13 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.19,
      "cam_y": 0.2,
      "cam_z": -1.14,
      "target_x": 0,
      "target_y": 0,
      "target_z": -1.3067,
      "radius": 0.1579,
      "js_name": "Umlenkrolle",
      "active_bone": "Umlenkrolle_1"
    },
    {
      "Schritt": 6,
      "Visual": null,
      "Title": "Feststeller",
      "Description": "an beiden Enden anbringen",
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.19,
      "cam_y": 0.2,
      "cam_z": -1.14,
      "target_x": 0,
      "target_y": 0,
      "target_z": -1.3067,
      "radius": 0.158,
      "js_name": "Feststeller",
      "active_bone": "Feststeller_1"
    },
    {
      "Schritt": 7,
      "Visual": null,
      "Title": "Seilführungen",
      "Description": "je nach Länge einsetzen, Seilführung anbringen.",
      "SlotNut": "x",
      "Notification_1": "Darauf achten, auf welcher Seite die Zugwagen fahren, um diese nicht zu blockieren",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.13,
      "cam_y": 0.23,
      "cam_z": -0.72,
      "target_x": 0,
      "target_y": 0,
      "target_z": -0.643,
      "radius": 0.0986,
      "js_name": "Abstandshalter",
      "active_bone": "Abstandsrolle_2_2"
    },
    {
      "Schritt": 8,
      "Visual": null,
      "Title": "Ableitrolle",
      "Description": "an dem Ende an dem gezogen wird anbringen",
      "SlotNut": "x",
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.2825,
      "cam_y": 1.254,
      "cam_z": 1.203,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0.47,
      "radius": 1,
      "js_name": "Ableitrolle",
      "active_bone": "Umlenkrolle_2"
    },
    {
      "Schritt": 9,
      "Visual": null,
      "Title": "Gegenspannrolle",
      "Description": "am Boden platzieren und befestigen",
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": "Befestigungsmaterial für Bodenfläche? Außerhalb der Systemgrenzen",
      "cam_x": 0.2825,
      "cam_y": 1.254,
      "cam_z": 1.203,
      "target_x": 0,
      "target_y": -1,
      "target_z": 0.47,
      "radius": 1,
      "js_name": "Gegenspannrolle",
      "active_bone": "Gegenspannrolle"
    },
    {
      "Schritt": 10,
      "Visual": null,
      "Title": "Vorhangmitte",
      "Description": "mit den Zugwagen-Positionen bestimmen und den gewünschten Überdeckungsabstand festlegen",
      "SlotNut": null,
      "Notification_1": "Meist werden die Überzugbügel komplett überdeckt",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 1.5,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 0.34,
      "js_name": "Vorhangmitte",
      "active_bone": "Laufwagen_ueberzugbuegel_1"
    }
  ]
}

var StaticContent = {};

staticContent.Vorhangschiene_Tutorialsteps.map((step, index)=>{
  StaticContent[step.js_name] = step;
});



export default StaticContent;