const staticContent = {
  "Vorhangschiene_Tutorialsteps": [
    {
      "Schritt": 1,
      "Visual": null,
      "Title": "Schienenteile",
      "Description": "mit zwei Verbindungsstiften zentriert und mit einem Schienenverbinder kraftschlüssig verbinden",
      "SlotNut": null,
      "Notification_1": "Später benötigte Einschubnutensteine vor dem Verbinden der Schienenteile in Schienennut schieben.",
      "Notification_2": "Der Verbindungsstift Edelstahl kann den Standard-Verbindungs-\nstift dort ersetzen, wo häufiger Auf- und Abbau der Schienen\nvorkommt (erleichtert das Auseinandernehmen der Schienenteile).",
      "Warning": null,
      "Tool_1": "Hammer",
      "Tool_2": "Zange",
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.33,
      "cam_y": 0.2,
      "cam_z": -0.13,
      "target_x": 0,
      "target_y": 0,
      "target_z": -0.4328,
      "radius": 0.1899,
      "js_name": "Schienenteile"
    },
    {
      "Schritt": 2,
      "Visual": null,
      "Title": "Abhängungen für Seilführung",
      "Description": "je nach Länge und Gewicht platzieren",
      "SlotNut": null,
      "Notification_1": "Die Abhängungen so ausrichten, dass eine Kollision mit den Seilzugbügeln dere Zugwagen ausgeschlossen ist.",
      "Notification_2": null,
      "Warning": "Darauf achten, dass nur Abhängungen zum Einsatz kommen, die zur Seilführungsart passen.",
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Seilfuehrung"
    },
    {
      "Schritt": 3,
      "Visual": null,
      "Title": "Rohrhaken",
      "Description": "an den Abhängungen montieren",
      "SlotNut": "x",
      "Notification_1": "Die Rohrhaken so einstellen, dass sie in eine Richtung geöffnet sind.",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": "Zange",
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": -0.4621,
      "cam_y": 0.1329,
      "cam_z": -0.7031,
      "target_x": 0.4927,
      "target_y": 0.069,
      "target_z": 0.2062,
      "radius": 0.1963,
      "js_name": "Rohrhaken"
    },
    {
      "Schritt": 4,
      "Visual": null,
      "Title": "Laststangen",
      "Description": null,
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": -3,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Laststangen"
    },
    {
      "Schritt": 5,
      "Visual": null,
      "Title": "Beide Zugwagen",
      "Description": "in der Mitte gegenläufig auf jeweils einer Seite einsetzen",
      "SlotNut": null,
      "Notification_1": "Auf die richtige Positionierung der Bügel achten.",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.29,
      "cam_y": 0.26,
      "cam_z": 0.39,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 0.35,
      "js_name": "Zugwagen"
    },
    {
      "Schritt": 6,
      "Visual": null,
      "Title": "Zweiradlaufwagen",
      "Description": "auf beiden Seiten je nach Länge anbringen",
      "SlotNut": null,
      "Notification_1": "gem. Ösenabstand alle 200 mmm (bei einem glatten Vorhang)",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0,
      "cam_y": 0,
      "cam_z": -0.9251,
      "target_x": 0.62,
      "target_y": 0.19,
      "target_z": -0.05,
      "radius": 0.5472,
      "js_name": "Zweilaufradwagen"
    },
    {
      "Schritt": 7,
      "Visual": null,
      "Title": "Umlenkrolle und Ableitrolle",
      "Description": "auf jeweils einer Seite anbringen (Ableitrolle an dem Ende, an dem gezogen wird)",
      "SlotNut": "x",
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "Schraubenschlüssel/Ratsche SW 13 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.19,
      "cam_y": 0.2,
      "cam_z": -1.14,
      "target_x": 0,
      "target_y": 0,
      "target_z": -1.2956,
      "radius": 0.1579,
      "js_name": "Umlenkrolle"
    },
    {
      "Schritt": 8,
      "Visual": null,
      "Title": "Feststeller",
      "Description": "an beiden Enden anbringen",
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.25,
      "cam_y": 0.29,
      "cam_z": -1.06,
      "target_x": 0,
      "target_y": 0,
      "target_z": -1.3108,
      "radius": 0.158,
      "js_name": "Feststeller"
    },
    {
      "Schritt": 9,
      "Visual": null,
      "Title": "Seilführungen",
      "Description": "je nach Länge einsetzen, Seilführung anbringen.",
      "SlotNut": "x",
      "Notification_1": "Darauf achten, auf welcher Seite die Zugwagen fahren, um diese nicht zu blockieren",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0.13,
      "cam_y": 0.23,
      "cam_z": -0.72,
      "target_x": 0,
      "target_y": 0,
      "target_z": -0.643,
      "radius": 0.0986,
      "js_name": "Abstandshalter"
    },
    {
      "Schritt": 10,
      "Visual": null,
      "Title": "Zuleitrolle",
      "Description": "an dem Ende an dem gezogen wird vor der Ableitrolle anbringen",
      "SlotNut": "x",
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "ISK 8 mm",
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Zuleitrolle"
    },
    {
      "Schritt": 11,
      "Visual": null,
      "Title": "Gegenspannrolle",
      "Description": "am Boden platzieren und befestigen",
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": "Befestigungsmaterial für Bodenfläche? Außerhalb der Systemgrenzen",
      "cam_x": 0,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Gegenspannrolle"
    },
    {
      "Schritt": 12,
      "Visual": null,
      "Title": "Vorhangmitte",
      "Description": "mit den Zugwagen-Positionen bestimmen und den gewünschten Überdeckungsabstand festlegen",
      "SlotNut": null,
      "Notification_1": "Meist werden die Überzugbügel komplett überdeckt",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": -1.5,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Vorhangmitte"
    },
    {
      "Schritt": 12,
      "Visual": null,
      "Title": "Seil",
      "Description": "einfädeln und die freien Enden an einem der beiden Zugwagen befestigen. Den zweiten Zugwagen ebenfalls mit dem Zugseil verbinden",
      "SlotNut": null,
      "Notification_1": "Seil nicht zu stark spannen, um leichtgängigen Lauf sicherzustellen.",
      "Notification_2": null,
      "Warning": null,
      "Tool_1": "Schraubenschlüssel/Ratsche SW 13 mm",
      "Tool_2": "ISK 5 mm",
      "Tool_3": "Kabelbinder",
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Seil"
    },
    {
      "Schritt": 13,
      "Visual": null,
      "Title": "Vorhang einhäng teaser",
      "Description": null,
      "SlotNut": null,
      "Notification_1": null,
      "Notification_2": null,
      "Warning": null,
      "Tool_1": null,
      "Tool_2": null,
      "Tool_3": null,
      "Tool_4": null,
      "Tool_5": null,
      "Fragen / Kommentare": null,
      "cam_x": 0,
      "cam_y": 0,
      "cam_z": 0,
      "target_x": 0,
      "target_y": 0,
      "target_z": 0,
      "radius": 1,
      "js_name": "Vorhang_einhaengen"
    }
  ]
}


var MaskPositions = {};

staticContent.Vorhangschiene_Tutorialsteps.map((step, index)=>{
  MaskPositions[step.js_name] = step;
});



export default MaskPositions;